kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: o7Yvc9OgkPFtlORzGlVYTac+DftiS3Mx9xBptgoiSwc=
      - identity: {}
